# Generated by Django 3.2 on 2021-05-02 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barrio')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('manzana', models.SmallIntegerField(blank=True, null=True, verbose_name='Manzana')),
                ('parcela', models.SmallIntegerField(blank=True, null=True, verbose_name='Parcela')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Extra')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.address', verbose_name='Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.province', verbose_name='Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='clients.city'),
        ),
    ]
